# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-MD5-File
version:      0.06
version_from: File.pm
installdirs:  site
requires:
    Digest::MD5:                   0
    LWP::UserAgent:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
